import type { Metadata } from "next";
import "./globals.css";
import { Inter, Roboto, Open_Sans } from "next/font/google"
import { ThemeProvider } from "next-themes";



const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
const open_sans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open_sans"
})
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${open_sans.variable} ${roboto.variable} ${inter.variable}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html >
  );
}
