apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: viora
  namespace: viora
  labels:
    app.kubernetes.io/part-of: viora
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - vioraa.tech
        - www.vioraa.tech
        - api.vioraa.tech
      secretName: viora-production-tls
  rules:
    - host: vioraa.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: viora-web
                port:
                  name: http
    - host: www.vioraa.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: viora-web
                port:
                  name: http
    - host: api.vioraa.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: viora-server
                port:
                  name: http
